create type "public"."gender" as enum ('male', 'female');

create type "public"."payment_methods" as enum ('efectivo', 'credito', 'debito', 'transferencia');

create type "public"."payment_state" as enum ('pagado', 'atrasado', 'pendiente');

create table "public"."categories" (
    "category_id" bigint generated by default as identity not null,
    "category_name" text,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."categories" enable row level security;

create table "public"."users" (
    "id" bigint generated by default as identity not null,
    "username" text not null default ''::text,
    "fullname" text not null default ''::text,
    "email" text not null default ''::text,
    "created_at" timestamp with time zone not null default now(),
    "gender" gender
);


alter table "public"."users" enable row level security;

alter table "public"."expenses" add column "category_id" bigint not null;

alter table "public"."expenses" add column "payment_method" payment_methods not null default 'efectivo'::payment_methods;

alter table "public"."expenses" add column "payment_state" payment_state not null default 'pagado'::payment_state;

alter table "public"."expenses" add column "user_id" bigint;

CREATE UNIQUE INDEX categories_id_key ON public.categories USING btree (category_id);

CREATE UNIQUE INDEX categories_pkey ON public.categories USING btree (category_id);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE UNIQUE INDEX users_pkey ON public.users USING btree (id);

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

alter table "public"."categories" add constraint "categories_pkey" PRIMARY KEY using index "categories_pkey";

alter table "public"."users" add constraint "users_pkey" PRIMARY KEY using index "users_pkey";

alter table "public"."categories" add constraint "categories_id_key" UNIQUE using index "categories_id_key";

alter table "public"."expenses" add constraint "public_expenses_category_id_fkey" FOREIGN KEY (category_id) REFERENCES categories(category_id) not valid;

alter table "public"."expenses" validate constraint "public_expenses_category_id_fkey";

alter table "public"."expenses" add constraint "public_expenses_user_id_fkey" FOREIGN KEY (user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE CASCADE not valid;

alter table "public"."expenses" validate constraint "public_expenses_user_id_fkey";

alter table "public"."users" add constraint "users_email_key" UNIQUE using index "users_email_key";

alter table "public"."users" add constraint "users_username_key" UNIQUE using index "users_username_key";

grant delete on table "public"."categories" to "anon";

grant insert on table "public"."categories" to "anon";

grant references on table "public"."categories" to "anon";

grant select on table "public"."categories" to "anon";

grant trigger on table "public"."categories" to "anon";

grant truncate on table "public"."categories" to "anon";

grant update on table "public"."categories" to "anon";

grant delete on table "public"."categories" to "authenticated";

grant insert on table "public"."categories" to "authenticated";

grant references on table "public"."categories" to "authenticated";

grant select on table "public"."categories" to "authenticated";

grant trigger on table "public"."categories" to "authenticated";

grant truncate on table "public"."categories" to "authenticated";

grant update on table "public"."categories" to "authenticated";

grant delete on table "public"."categories" to "service_role";

grant insert on table "public"."categories" to "service_role";

grant references on table "public"."categories" to "service_role";

grant select on table "public"."categories" to "service_role";

grant trigger on table "public"."categories" to "service_role";

grant truncate on table "public"."categories" to "service_role";

grant update on table "public"."categories" to "service_role";

grant delete on table "public"."users" to "anon";

grant insert on table "public"."users" to "anon";

grant references on table "public"."users" to "anon";

grant select on table "public"."users" to "anon";

grant trigger on table "public"."users" to "anon";

grant truncate on table "public"."users" to "anon";

grant update on table "public"."users" to "anon";

grant delete on table "public"."users" to "authenticated";

grant insert on table "public"."users" to "authenticated";

grant references on table "public"."users" to "authenticated";

grant select on table "public"."users" to "authenticated";

grant trigger on table "public"."users" to "authenticated";

grant truncate on table "public"."users" to "authenticated";

grant update on table "public"."users" to "authenticated";

grant delete on table "public"."users" to "service_role";

grant insert on table "public"."users" to "service_role";

grant references on table "public"."users" to "service_role";

grant select on table "public"."users" to "service_role";

grant trigger on table "public"."users" to "service_role";

grant truncate on table "public"."users" to "service_role";

grant update on table "public"."users" to "service_role";


